### ISSUE TITLE
new complaints are no longer showing in `Meldungen` view

### ISSUE THREAD

**Issue by foss-** [weg-li/weg-li-ios#76]
After filing a few complaints by tapping the email button and sending the email, none of those complaints show up in `Meldungen` view or weg.li webview for that matter.

**Comment by mltbnz** [comment]
When you are sending a notice via email it means the app is not connected to your account which can be done by entering using your api token and adding it to the app.
The issue with adding notices from sent mails is to really be sure that they have been sent since that technically is not fully reliable. So for this stage it has not been part of the scope

**Comment by mltbnz** [comment]
Hi.
Since some time now there have been changes to the API and the updated app can make it to the store since the website is missing some technical requirement. 

So the AppStore version is broken and won't be updated. It'll probably disappear in the next weeks anyways.

Sorry for that.

**Comment by BSVogler** [comment]
Do you know if my reports still got sent? If not I would sent them via the website again.

**Comment by mltbnz** [comment]
When you set up the api token in the app it should have sent it via the wegli server. So when you log in too the website you should see the notice you sent with the app. If it's not there it wasn't sent

**Comment by phoet** [comment]
They still did not approve the app? 😒  I will have a look into the login via Apple thing next week, maybe something has improved on that front.

**Comment by mltbnz** [comment]
No there is still the issue that the website needs to have a log in with Apple option. Does it?

Until it has that the updates won't go through. Well maybe if I get lucky and some review person is not paying too much attention 😄

**Comment by phoet** [comment]
we failed implementing the sign-in-with-apple bc they dont care about industry standards and make it so that it does not work with omniauth which is usually plug and play. 

omniauth has become such a PITA recently, with elnos twitter leading the way in simply disabling all unpaid developer apps that had used twitter auth before...

**Comment by phoet** [comment]
sign in with apple is now finally implemented. so no blocker here any more. sorry for the inconvenience

**Comment by mltbnz** [comment]
Nice 👍 that's really cool to hear. 

I'll try to trigger an update next week then

**Comment by phoet** [comment]
@mltbnz did it work?

i've queud up a set of changes that will be relevant for the app as well https://github.com/weg-li/weg-li/pull/722

**Comment by mltbnz** [comment]
I did update the app in more then 1 place and will trigger an update soon. Hopefully. 

Uploading an image failed and I need to find out why. Also updated our slack thread on that matter
