### ISSUE TITLE
Weg-li on iOS 16.3.1 - Entry not possible - freezing

### ISSUE THREAD

**Issue by HerMatth** [weg-li/weg-li-ios#83]
Hi Team

a new entry not possible:
 > Photo upload is hanging often
 > License plate recognition not working
 > details of the Car / case cannot be insert - App is hanging/freeze every time.

**Comment by HerMatth** [comment]
Note:
The behavior can be observed if I will select more than one photo from gallery at the same time…
If I will select the photos in single steps and start with details before it will works…

**Comment by mltbnz** [comment]
Thanks for bringing this up. I also observed it and will check what the issue is asap. 

Note that atm an update to the store version is not possible since Apple requires an update on the website

**Comment by HerMatth** [comment]
Today I try to open a new case - all data has been filled correctly. 
But last service: sending & update was not possible - the new message was hanging and not sent (freezing).

Also the single taken and attached photos could not be shown/displayed in enlarged. These also not saved in gallery - to open case later via web-Portal 😥

After restart Weg-li App the data and case data was deleted/lost…

**Comment by mltbnz** [comment]
Hi. I am sitting on the crash right now :) and am trying to reproduce it. 

Regarding sending a notice: still not possible atm since the weg.li API was updated and the store app is not using the updated format yet. The update is blocked since Apple requires us to add sign in with apple to the website before we can continue and I have no idea when someone is going to add that basically.

You can try out the TestFlight version. That one should be able to send a notice.
https://testflight.apple.com/join/3SCoUsnL

**Comment by nonsavant** [comment]
Any news on this? I'm observing similar behaviour and it unfortunately renders the app almost unuseable.

Would sideloading - now possible in the EU - be a way around the apple store restrictions mentioned above?

**Comment by phoet** [comment]
The app is no longer supported unfortunately.
